import { Ingredient } from '@/types/ingredient';
import { QuickCommercePlatform } from '@/types/shoppingList';
import * as Clipboard from 'expo-clipboard';
import * as Sharing from 'expo-sharing';

export const shoppingListService = {
  formatForPlatform(ingredients: Ingredient[], platform: QuickCommercePlatform): string {
    const grouped = this.groupByCategory(ingredients);
    let text = '';

    const titles = {
      zepto: '🛒 Shopping List for Zepto\n\n',
      blinkit: '🛍️ Blinkit Shopping List\n\n',
      instamart: '🛒 Swiggy Instamart List\n\n',
      generic: '📋 Shopping List\n\n',
    };

    text += titles[platform];

    // Sort categories alphabetically for consistency
    const sortedCategories = Object.keys(grouped).sort();

    sortedCategories.forEach((category) => {
      text += `📦 ${category.toUpperCase()}\n`;
      grouped[category].forEach((item) => {
        const checkbox = item.checked ? '☑' : '☐';
        text += `  ${checkbox} ${item.name} - ${item.quantity} ${item.unit}\n`;
      });
      text += '\n';
    });

    text += '---\nGenerated by Plan My Meal 🍽️';
    return text;
  },

  groupByCategory(ingredients: Ingredient[]): Record<string, Ingredient[]> {
    const grouped: Record<string, Ingredient[]> = {};

    ingredients.forEach((ing) => {
      if (!grouped[ing.category]) {
        grouped[ing.category] = [];
      }
      grouped[ing.category].push(ing);
    });

    return grouped;
  },

  async copyToClipboard(text: string): Promise<void> {
    await Clipboard.setStringAsync(text);
  },

  async share(text: string): Promise<void> {
    try {
      const isAvailable = await Sharing.isAvailableAsync();
      if (isAvailable) {
        await Sharing.shareAsync(text, {
          mimeType: 'text/plain',
          dialogTitle: 'Share Shopping List',
        });
      } else {
        // Fallback to clipboard if sharing is not available
        await this.copyToClipboard(text);
      }
    } catch (error) {
      console.error('Error sharing:', error);
      // Fallback to clipboard
      await this.copyToClipboard(text);
    }
  },

  getPlatformColor(platform: QuickCommercePlatform): string {
    const colors = {
      zepto: '#6C4AB6',
      blinkit: '#F98E04',
      instamart: '#FF5200',
      generic: '#6B7280',
    };
    return colors[platform] || colors.generic;
  },

  getPlatformIcon(platform: QuickCommercePlatform): string {
    const icons = {
      zepto: '⚡',
      blinkit: '🛍️',
      instamart: '🛒',
      generic: '📋',
    };
    return icons[platform] || icons.generic;
  },
};
